[General]
cfgbase                     = "/home/suqikuai777/Program/SBI_Void/simulator/fastpm/Simtool/Pipeline/cfgs/Cosmology/"
cfgsubbase                  = "cosmo"

; >==== 1. Read cosmology parameters from file ====<
input                       = "cosmo_list.json"
; >================================================<

; >==== 2. Set specific cosmological parameters ====<
; n_fix_params              = 5
; fix_cosmo_names           = hubble, OmegaM, Omegab, ns, S8
; fix_cosmo_vals            = 0.6727, 0.3156, 0.0491, 0.9667, 0.852
; >=================================================<

[FastPM]
boxsize                     = 100
npart                       = 64
nrlzs                       = 1
seedini                     = 10410
time_step                   = "linspace(0.01, 1, 40)"
redshifts                   = 0.3
snapdir                     = "/home/suqikuai777/Program/SBI_Void/simulator/fastpm/catalogs/Cosmology/"
FOF                         = False
ROCKSTAR                    = True

[Convert]
nfile                       = 2
precision                   = "f4"
outputbase                  = "gadget/snapshot_"

[ROCKSTAR]
force_res                   = 0.003
parallel                    = 1
num_readers                 = 32
num_writers                 = 32
process_per_machine         = 32
outputbase                  = "rstar/"

[SHAM]
nrlzs                       = 1
seedini                     = 33000

; >==== 1. set the paramfile ====<
input                       = "SHAM_list.json"
; >==============================<

; >==== 2. set the parameter ====<
; fix_param_vals            = 1.5
; >==============================<

ref_num_den                 = 3.5e-4
feature                     = "mvir"
z_space                     = False

outputbase                  = "SHAM"